savePrefix: ""
autoInstallPeers: false
strictPeerDependencies: true
minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: "no-downgrade"

ignoredOptionalDependencies:
  - "@pkgjs/parseargs"
  - fsevents

allowBuilds:
  esbuild: false
