name: emscripten

runs:
  using: composite
  steps:
    - name: Setup emscripten cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ./.emscripten
        key: ${{ runner.os }}-emscripten-${{ hashFiles('build_docker.sh') }}
        restore-keys: |
          ${{ runner.os }}-emscripten

    - name: Build emscripten
      uses: docker://emscripten/emsdk:6.0.7@sha256:71190e58eab340c692c0c3bb9741705f5c9625766a561c906dc6c01b1ed6d761
      with:
        args: ./build.sh
