name: emscripten

runs:
  using: composite
  steps:
    - name: Setup emscripten cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ./.emscripten
        key: ${{ runner.os }}-emscripten-${{ hashFiles('build_docker.sh') }}
        restore-keys: |
          ${{ runner.os }}-emscripten

    - name: Build emscripten
      uses: docker://emscripten/emsdk:4.0.5@sha256:5aea37132ad0827908065a5d7432d2f4048011dce7169aa1ab3441b0720312e2
      with:
        args: ./build.sh
