name: emscripten

runs:
  using: composite
  steps:
    - name: Setup emscripten cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ./.emscripten
        key: ${{ runner.os }}-emscripten-${{ hashFiles('build_docker.sh') }}
        restore-keys: |
          ${{ runner.os }}-emscripten

    - name: Build emscripten
      uses: docker://emscripten/emsdk:6.0.3@sha256:bb0910e6a18bb9bd7cb31ae4ed40f9073148b78cb2cdb8ea8676454e0d85425c
      with:
        args: ./build.sh
