name: emscripten

runs:
  using: composite
  steps:
    - name: Setup emscripten cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
      with:
        path: ./.emscripten
        key: ${{ runner.os }}-emscripten-${{ hashFiles('build_docker.sh') }}
        restore-keys: |
          ${{ runner.os }}-emscripten

    - name: Build emscripten
      uses: docker://emscripten/emsdk:4.0.3@sha256:8dd584d0b33bfae94f57cc000adf02d94621aaf94b848371d98a24b891b84ee5
      with:
        args: ./build.sh
