name: emscripten

runs:
  using: composite
  steps:
    - name: Setup emscripten cache
      uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4
      with:
        path: ./.emscripten
        key: ${{ runner.os }}-emscripten
        restore-keys: |
          ${{ runner.os }}-emscripten

    - name: Build emscripten
      uses: docker://emscripten/emsdk:3.1.68@sha256:c7853fb096579c951797b97e99a319df7476c46c08d5fe0ba9e4399f6b397227
      with:
        args: ./build.sh
