name: emscripten

runs:
  using: composite
  steps:
    - name: Setup emscripten cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ./.emscripten
        key: ${{ runner.os }}-emscripten-${{ hashFiles('build_docker.sh') }}
        restore-keys: |
          ${{ runner.os }}-emscripten

    - name: Build emscripten
      uses: docker://emscripten/emsdk:5.0.6@sha256:e1b3e665245524ac6b62b180f9ccf9bd22308e6bb034f5fd9090df54fdbdfba6
      with:
        args: ./build.sh
