name: e2e

runs:
  using: composite
  steps:
    - name: End-to-End
      uses: phi-ag/run-playwright@df747e2671dd5c166a481e97859732daf46cd6d4 # v1
      with:
        version: v1.56.0-noble@sha256:35246d87a7c88ea9b771c65d33171b2611b02a8253b4b12ce6f94376c55f99f2
        options: -v ${STORE_PATH}:${STORE_PATH}
        run: |
          corepack enable
          corepack prepare --activate

          pnpm config set store-dir ${STORE_PATH}
          pnpm install --frozen-lockfile
          pnpm test:e2e
