name: e2e

runs:
  using: composite
  steps:
    - name: End-to-End
      uses: phi-ag/run-playwright@128f1acbb01b9d8fbe039e8d706fb09523119638 # v1
      with:
        version: v1.54.2-noble@sha256:18b4bcff4f8ba0ac8c44b09f09def6a4f6cb8579e5f26381c21f38b50935d5d8
        options: -v ${STORE_PATH}:${STORE_PATH}
        run: |
          corepack enable
          corepack prepare --activate

          pnpm config set store-dir ${STORE_PATH}
          pnpm install --frozen-lockfile
          pnpm test:e2e
