name: e2e

runs:
  using: composite
  steps:
    - name: End-to-End
      uses: phi-ag/run-playwright@5a83095c61d9461619391a8ee56fc1959acad29c # v1
      with:
        version: v1.64.0-noble@sha256:06a9939e57531807f8d5fd76ce44b53165ffb7d7501d87ab10e285c20b1e971f
        options: -v ${STORE_PATH}:${STORE_PATH}
        run: |
          corepack enable
          corepack prepare --activate

          pnpm config set store-dir ${STORE_PATH}
          pnpm install --frozen-lockfile
          pnpm test:e2e
