name: Release Please

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  attestations: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: recursive

      - name: Emscripten
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/emscripten

      - name: Restore
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/restore

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

      - name: Generate SBOM
        run: pnpm --reporter=silent sbom | tee sbom.cdx.json | jq

      - name: Attest
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/attest-sbom@5026d3663739160db546203eeaffa6aa1c51a4d6 # v1
        with:
          subject-path: ./src/argon2.wasm
          sbom-path: sbom.cdx.json

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./src/argon2.wasm
