name: Release Please

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  attestations: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          submodules: recursive

      - name: Export commit timestamp
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/source-date-epoch

      - name: Emscripten
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/emscripten

      - name: Restore
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/restore

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

      - name: Generate SBOM
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/sbom

      - name: Attest
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/attest-sbom@bd218ad0dbcb3e146bd073d1d9c6d78e08aa8a0b # v2
        with:
          subject-path: src/argon2.wasm
          sbom-path: sbom.cdx.json

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} src/argon2.wasm sbom.cdx.json
